# Generated by Django 3.0.5 on 2020-04-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200426_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
